# Generated by Django 4.0.5 on 2022-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hex_color',
            field=models.CharField(max_length=7, verbose_name='Цвет'),
        ),
    ]
