# Generated by Django 4.0.5 on 2022-07-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hex_color',
            field=models.CharField(choices=[('#FFA500', 'orange'), ('#008000', 'green'), ('#800080', 'purple'), ('#FF0000', 'red'), ('#FFFF00', 'yellow'), ('#0000FF', 'blue'), ('#C0C0C0', 'silver'), ('#000000', 'black')], default='#000000', max_length=7, verbose_name='Цвет'),
        ),
    ]
